姓名: 安卓安装包

在……之上:
推:
分支机构:
      - 主要的

工作:
建立:
连续的: Ubuntu-最新

步骤:
      - 姓名: 拉取代码
uses: 操作/结帐@v4

-姓名: 配置JDK
uses: 操作/设置-Java@v4
和……一起:
java版: '17'
分布: 'temurin'

      - 姓名: 打包APPK
跑: |
chmod+x gradlew
./gradlew装配调试

      - 姓名: 上传APK
uses: 操作/上载工件@v4
和……一起:
姓名: app-debug.apk
路径: app/build/outputs/apk/debug/app-debug.apk
